import type { GiveawayPublic, WinnerSnapshot } from "./types"

export const mockGiveaways: GiveawayPublic[] = [
  {
    slug: "macbook-pro-m3",
    title: "MacBook Pro M3 Max",
    prizeTitle: 'MacBook Pro 16" M3 Max',
    imageUrl: "/macbook-pro-laptop.png",
    ticketPrice: 5.0,
    endsAt: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    status: "active",
    prizeValue: "$3,499",
    images: ["/macbook-pro-laptop.png", "/macbook-side-view.jpg", "/macbook-open.jpg"],
    bundles: [
      { qty: 1, price: 5.0 },
      { qty: 5, price: 20.0, label: "Best Value" },
      { qty: 10, price: 35.0, label: "Max Entries" },
    ],
    socialProof: {
      entrantCountBucket: "2.5k+",
      recentAvatars: [
        "/person-avatar-1.png",
        "/diverse-person-avatar-2.png",
        "/person-avatar-3.png",
        "/person-avatar-4.png",
      ],
    },
    rulesText:
      "Open to residents of the United States aged 18+. No purchase necessary. Entry period ends at the date/time shown. Winner will be selected randomly and notified via email within 48 hours of draw. Prize must be claimed within 14 days. See full terms and conditions for complete rules.",
    faqSnippet: "How do I enter? What are my chances of winning?",
  },
  {
    slug: "ps5-bundle",
    title: "PlayStation 5 Bundle",
    prizeTitle: "PS5 + 3 Games",
    imageUrl: "/playstation-5-console.png",
    ticketPrice: 3.0,
    endsAt: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    status: "ending-soon",
    prizeValue: "$599",
    bundles: [
      { qty: 1, price: 3.0 },
      { qty: 5, price: 12.0, label: "Popular" },
      { qty: 10, price: 20.0, label: "Best Value" },
    ],
    socialProof: {
      entrantCountBucket: "5k+",
      recentAvatars: ["/gamer-avatar-1.png", "/gamer-avatar-2.png", "/gamer-avatar-3.png"],
    },
    rulesText:
      "Open to residents of the United States aged 18+. No purchase necessary. Entry period ends at the date/time shown. Winner will be selected randomly and notified via email within 48 hours of draw.",
    faqSnippet: "When will the winner be announced?",
  },
  {
    slug: "iphone-15-pro",
    title: "iPhone 15 Pro Max",
    prizeTitle: "iPhone 15 Pro Max 256GB",
    imageUrl: "/iphone-15-pro-smartphone.jpg",
    ticketPrice: 4.0,
    endsAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    status: "active",
    prizeValue: "$1,199",
    bundles: [
      { qty: 1, price: 4.0 },
      { qty: 5, price: 18.0, label: "Save 10%" },
      { qty: 10, price: 32.0, label: "Best Value" },
    ],
    socialProof: {
      entrantCountBucket: "1k+",
      recentAvatars: ["/tech-enthusiast-1.jpg", "/tech-enthusiast-2.jpg"],
    },
    rulesText:
      "Open to residents of the United States aged 18+. No purchase necessary. Entry period ends at the date/time shown. Winner will be selected randomly and notified via email within 48 hours of draw.",
  },
]

export const mockWinners: WinnerSnapshot[] = [
  {
    name: "Sarah Martinez",
    avatarUrl: "/professional-woman-headshot.png",
    prizeTitle: 'MacBook Pro 16" M3 Max',
    giveawayTitle: "MacBook Pro M3 Max",
    announcedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    giveawaySlug: "macbook-pro-m3",
    quote: "I can't believe I won! This is going to make my work so much easier. Thank you!",
  },
  {
    name: "James Chen",
    avatarUrl: "/professional-man-headshot.png",
    prizeTitle: "PlayStation 5 Pro",
    giveawayTitle: "PS5 Pro Bundle",
    announcedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    giveawaySlug: "ps5-bundle",
  },
  {
    name: "Emily Rodriguez",
    avatarUrl: "/smiling-woman-headshot.png",
    prizeTitle: "iPhone 15 Pro Max",
    giveawayTitle: "iPhone 15 Pro Giveaway",
    announcedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    giveawaySlug: "iphone-15-pro",
  },
  {
    name: "Michael Thompson",
    avatarUrl: "/professional-man.jpg",
    prizeTitle: "AirPods Pro 2",
    giveawayTitle: "AirPods Pro Giveaway",
    announcedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    name: "Jessica Williams",
    avatarUrl: "/smiling-woman.png",
    prizeTitle: "iPad Air M2",
    giveawayTitle: "iPad Air Giveaway",
    announcedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    name: "David Park",
    avatarUrl: "/young-professional-man.png",
    prizeTitle: "Nintendo Switch OLED",
    giveawayTitle: "Nintendo Switch Bundle",
    announcedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    name: "Amanda Foster",
    avatarUrl: "/professional-woman-smiling.png",
    prizeTitle: "Apple Watch Series 9",
    giveawayTitle: "Apple Watch Giveaway",
    announcedAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    name: "Robert Johnson",
    avatarUrl: "/friendly-man.jpg",
    prizeTitle: "DJI Mini 4 Pro Drone",
    giveawayTitle: "DJI Drone Giveaway",
    announcedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    name: "Lisa Anderson",
    avatarUrl: "/happy-woman.jpg",
    prizeTitle: "Dyson Airwrap",
    giveawayTitle: "Dyson Airwrap Giveaway",
    announcedAt: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    name: "Kevin Lee",
    avatarUrl: "/young-man-smiling.png",
    prizeTitle: "Sony WH-1000XM5 Headphones",
    giveawayTitle: "Sony Headphones Giveaway",
    announcedAt: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    name: "Rachel Green",
    avatarUrl: "/woman-with-glasses.png",
    prizeTitle: "Kindle Paperwhite",
    giveawayTitle: "Kindle Giveaway",
    announcedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    name: "Brandon Davis",
    avatarUrl: "/casual-man.png",
    prizeTitle: "GoPro Hero 12",
    giveawayTitle: "GoPro Action Camera Giveaway",
    announcedAt: new Date(Date.now() - 33 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    name: "Nicole Taylor",
    avatarUrl: "/professional-woman-headshot.png",
    prizeTitle: "Ring Video Doorbell Pro",
    giveawayTitle: "Smart Home Giveaway",
    announcedAt: new Date(Date.now() - 36 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    name: "Christopher Moore",
    avatarUrl: "/diverse-businessman.png",
    prizeTitle: "Bose QuietComfort Earbuds",
    giveawayTitle: "Bose Earbuds Giveaway",
    announcedAt: new Date(Date.now() - 39 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    name: "Melissa White",
    avatarUrl: "/smiling-woman-portrait.png",
    prizeTitle: "Instant Pot Duo Plus",
    giveawayTitle: "Kitchen Appliance Giveaway",
    announcedAt: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
